### ISSUE TITLE
JPEG image produces unrecognized file format error

### ISSUE THREAD

**Issue by jakowenko** [nodeca/probe-image-size#68] opened 2021-11-09 21:20 UTC
I have what I believe is a valid JPEG image from a camera and when I try to obtain the size I get the `ProbeError: unrecognized file format` message.

```javascript
const sizeOf = require('probe-image-size');

(async () => {
  console.log(
    await sizeOf(
      'https://user-images.githubusercontent.com/1081811/141005965-09e60140-5a30-42ab-989a-dea0c3c361d7.jpg'
    )
  );
})();
```
```
reject(last_error || new ProbeError('unrecognized file format', 'ECONTENT'));
                           ^
ProbeError: unrecognized file format
    at ParserStream.parserEnd (/Users/Jako/Dev/github/double-take-alt/api/node_modules/probe-image-size/stream.js:39:28)
    at Object.onceWrapper (node:events:509:28)
    at ParserStream.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONTENT'
}
```
![snapshot](https://user-images.githubusercontent.com/1081811/141005965-09e60140-5a30-42ab-989a-dea0c3c361d7.jpg)

**Comment by puzrin** [comment] 2021-11-09 22:13
Quick reproduce:

```sh
node ./support/dump.js https://user-images.githubusercontent.com/1081811/141005965-09e60140-5a30-42ab-989a-dea0c3c361d7.jpg
```

**Comment by puzrin** [comment] 2021-11-10 18:43
@jakowenko file seems partially broken or non-standard (investigation in progress). Could you describe details, how you got it? Camera model, photo params and so on. Anything about how to reproduce images of this kind.

**Comment by rsteckler** [comment] 2021-11-10 19:00
The image comes from a Dahua Camera with official Dahua firmware
Device Type:  IPC-T5442T-ZE
System Version:  V2.820.0000000.5.R, Build Date: 2021-07-05

The image is pulled by hitting the camera's "snapshot" url:  http://ip_address/cgi-bin/snapshot.cgi

The camera is behind a private network, so you won't be able to pull more images from it, but I'm happy to grab as many as you need and send them over.  I've looked at four and all had the same issue within probe-image-size and the same error.

**Comment by jakowenko** [comment] 2021-11-10 19:01
FYI @puzrin, I originally created the ticket on behalf of @rsteckler, which is why I asked him to provide that info.

**Comment by puzrin** [comment] 2021-11-10 19:24
Also, if possible, please provide more such photos. Currently we have two:

- https://user-images.githubusercontent.com/1081811/141005521-d414b5a9-a8ab-4731-a842-f624bc13d456.jpg
- https://user-images.githubusercontent.com/1081811/141005965-09e60140-5a30-42ab-989a-dea0c3c361d7.jpg

That's enough to prove "problem is reproducible", but i'd like to understand details - is that from new camera, old camera, and why we missed such case.

**Comment by jakowenko** [comment] 2021-11-10 19:39
Oops, the one with the person should not be included. Let me edit that out of the original issue. Can you remove from your comment too please.

I'll have @rsteckler provide some more.

**Comment by rsteckler** [comment] 2021-11-10 19:42
It's a relatively new camera, released early 2020, but I don't imagine it's any different than what other Dahua cameras produce.  
Here are more images:
![4](https://user-images.githubusercontent.com/1714230/141180642-b329f4b8-22e4-4833-aec5-fef01c28c0ee.jpg)
![3](https://user-images.githubusercontent.com/1714230/141180655-c17aa1c3-a23b-4de6-bfbb-c930b839a1e9.jpg)

Here's one I generated with a slightly different URL.  Curious if this one is any different?:
![5](https://user-images.githubusercontent.com/1714230/141181967-7df328db-a693-4e05-a6cb-e9b466ddf923.jpeg)

I'm happy to grab as many as you need, but the camera itself is on my private network and I'm pretty hesitant to expose it publicly.

**Comment by rsteckler** [comment] 2021-11-10 19:42
(and as menitoned, please remove the image with my face in it :) )

**Comment by puzrin** [comment] 2021-11-10 19:52
- I removed requested links and don't need any private info.
- This bug will be fixed.

My question is about camera model. Need to understand who can produce such "strange" images. Difference from common - multiple `0x00` between jpeg segments.

- This is not described in standard.
- Some utilities like `/usr/bin/file` don't understand such files too.
- Browsers understand such images.

**Comment by rsteckler** [comment] 2021-11-10 19:55
The camera model is [Dahua IPC-T5442T-ZE](https://www.dahuasecurity.com/products/All-Products/Network-Cameras/WizMind-Series/5-Series/4MP/IPC-HDW5442T-ZE) 

It's become pretty popular in the security community in the last year.

Appreciate you implementing a fix even though these seems like an edge case and is being caused by a non-standards-compliant device.

**Closed** 2021-11-11 15:56 UTC
Labels: bug

**Comment by jakowenko** [comment] 2021-11-11 20:22
Thank you @rlidwka, do you know when this will be included in the next release?

**Comment by puzrin** [comment] 2021-11-12 01:44
See 7.2.2 with fixes.
